version: '2'

services: 
  web:
    image: deals_app:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    env_file: .env

  db:
    image: postgres:latest
    volumes: 
      - db_dir:/var/lib/postgresql/data
    env_file: .env

volumes:
  # web_dir:
  db_dir: